apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: person-service
build:
  artifacts:
    - image: person-service
      docker:
        dockerfile: Dockerfile
  local:
    push: false
deploy:
  kubectl:
    manifests:
      - src/main/kubernetes/*.yml
  kustomize:
    paths:
      - k8s
