spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/claudeai-dev
    username: claude
    password: claude
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/claude
          audience: pl.piomin.services
